import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
    <div className="scrollbar-hide" id="scrollbar-hide">
      <Head>
        <title>kristineCodes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col items-center justify-center bg-charcoal" >

      <h1 className="font-audreyMedium text-3xl uppercase text-white">
          Hi, my name is Kristine,
        </h1>
        <h1 className="font-bodyThin text-2xl  text-white">
          and I'm a full-stack software developer.
          With a front-end preference but does not shy away from the backend.
        </h1>
        <p className="font-audreyMediumOblique uppercase text-white">
        <br />
        <br />
          And this is my 
        </p>
        
        <h1 className="mb-5 font-heading text-5xl text-white">port·​fo·​lio</h1>
        <p className="text-center font-bodyThinItalic text-white mr-10 ml-10">
        <span className="hover:line-through decoration-coffee">
          1 : a hinged cover or flexible case for carrying loose papers,
          pictures, or pamphlets
          </span>
          <br />
          <span className="hover:line-through decoration-mint">
          2 [from the use of such a case to carry documents of state] : the
          office and functions of a minister of state or member of a cabinet
          </span>
          <br />
          <span className="hover:line-through decoration-creme">
          3 : the securities held by an investor : the commercial paper held by
          a financial house (such as a bank)
          </span>
          <br />
          <span className="hover:line-through decoration-white">
          4 : a set of pictures (such as drawings or photographs) usually bound
          in book form or loose in a folder
          </span>
          <span className="hover:underline decoration-orange">
          <br />5 : a selection of work
          compiled over a period of time and used for assessing performance or
          progress
          </span>
        </p>
        <br />
        <div id="scroll-title" className="text-creme mt-10">
            Scroll
          </div>
          <div id="scroll-down" className="bg-orange"></div>
      </div>

      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-charcoal to-mint">
    
      </div>

      <div className="w-screen bg-gradient-to-b from-mint to-creme">
        <main
          className="flex min-h-screen flex-col items-center justify-center"
          id="scrollbar-hide"
        >
          <p className="font-bodyRegularItalic">It all started with a</p>
          <h1 className="mb-3 font-heading text-5xl tracking-widest hover:tracking-wide">
            Hello World;
          </h1>
          <p className="font-bodyRegularItalic">and I knew I was hooked.</p>
        </main>
      </div>
      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-creme to-coffee">
      <p className="mb-5 font-heading text-5xl">study hero</p>
      </div>
      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-coffee to-orange">
      <p className="mb-5 font-heading text-5xl">minimize</p>
      </div>
      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-orange to-charcoal">
      <p className="mb-5 font-heading text-5xl">tokyo noire</p>
      </div>
      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-charcoal to-charcoal">
        <h1 className="text-white text-5xl font-heading">contact me</h1>
      </div>
      </div>
    </>
  );
};

export default Home;

{
  /* <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
  <h1 className="text-5xl font-bodyRegular tracking-tight text-white sm:text-[5rem]">
    CREATE <span className="text-[hsl(280,100%,70%)]">T3</span> App
  </h1>
  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
    <Link
      className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
      href="https://create.t3.gg/en/usage/first-steps"
      target="_blank"
    >
      <h3 className="text-2xl font-audreyBold uppercase">First Steps →</h3>
      <div className="text-lg font-bodyThin">
        Just the basics - Everything you need to know to set up your
        database and authentication.
      </div>
    </Link>
    <Link
      className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
      href="https://create.t3.gg/en/introduction"
      target="_blank"
    >
      <h3 className="text-2xl font-audreyMedium">Documentation →</h3>
      <div className="text-lg font-bodyThin">
        Learn more about Create T3 App, the libraries it uses, and how
        to deploy it.
      </div>
    </Link>
  </div>
  <p className="text-2xl text-white">
    {hello.data ? hello.data.greeting : "Loading tRPC query..."}
  </p>
</div> */
}
