import { type NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import ProgressBar from "react-progressbar-on-scroll";
import picture1 from "/public/DSCF0571.jpg";
import picture2 from "/public/DSCF0576.jpg";
import picture3 from "/public/DSCF0604.jpg";
import picture4 from "/public/DSCF0609.jpg";
import picture5 from "/public/DSCF0639.jpg";
import picture6 from "/public/DSCF0598.jpg";
import Image from "next/image";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import NavBar from "../components/NavBar";

// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  gsap.registerPlugin(ScrollTrigger);

  useEffect(() => {
    gsap.fromTo(
      "#picture1",
      { x: -10000 },
      {
        x: 0,
        duration: 9,
        scrollTrigger: { trigger: "#picture1", start: "top 60%", end: "top 30%" ,scrub:true, toggleActions:"restart none none none"},
      }
    );
    gsap.fromTo(
      ".picture2",
      { x: 10000 },
      {
        x: 0,
        duration: 9,
        scrollTrigger: { trigger: "#picture1", start: "top 60%", end: "top 30%",  scrub:true, toggleActions:"restart none none none"},
      }
    );
    gsap.fromTo(
      ".picture3",
      { x: -10000 },
      {
        x: 0,
        duration: 9,
        scrollTrigger: { trigger: "#picture1", start: "top 60%", end: "top 30%", scrub:true, toggleActions:"restart none none none"},
      }
    );
    
    gsap.fromTo(
      ".picture5",
      { x: 10000 },
      {
        x: 0,
        duration: 9,
        scrollTrigger: { trigger: "#picture1", start: "top 60%", end: "top 30%",  scrub:true, toggleActions:"restart none none none"},
      }
      );
      gsap.fromTo(
        ".picture4",
        { scale: 0 },
        {
          scale: 1,
          duration: 9,
          scrollTrigger: { trigger: "#picture1", start: "top 50%", end: "top 30%",  scrub:true, toggleActions:"restart none none none"},
        }
      );
      gsap.fromTo("#name",{y:-3000},{y:0, duration:2})
    }
  
  , []);
  return (
    <>
      <Head>
        <title>whimsicalCoder;</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <ProgressBar
        color="#DD8E58"
        height={10}
        direction="right"
        position="top"
        gradient={true}
        gradientColor="#2B2129"
      />
<div className="flex w-screen flex-col items-center justify-center bg-charcoal">
        <p id="name" className="mt-40 text-center  text-3xl">👋🏼</p>
        <h1 className="mt-3 text-center  font-audreyMedium text-3xl uppercase text-white">
          Hi, my name is Kristine,
        </h1>
        <h1 className="text-center font-bodyThin  text-2xl text-white">
          and I'm a full-stack software developer based in Tokyo, Japan.
        </h1>
        <div id="scroll-title" className="mt-36 text-mint">
          Scroll
        </div>
        <div id="scroll-down" className="bg-orange"></div>
  
</div>
      <div className="flex w-screen flex-col items-center justify-center bg-charcoal">
        <div className="mt-36 grid grid-cols-3">
          <Image
            className="col-span-2 grid h-full"
            id="picture1"
            alt="picture1"
            src={picture1}
          />
          <Image className="picture2" alt="picture6" src={picture6} />
          <Image className="picture3" alt="picture2" src={picture2} />
          <Image className="picture5" alt="picture5" src={picture5} />
          <Image className="picture4" alt="picture4" src={picture4} />
        </div>
      </div>
      <div className="flex w-screen flex-col items-center justify-center bg-charcoal">
        <p className="mt-20 font-audreyMediumOblique uppercase text-white">
          <br />
          <br />
          And this is my
        </p>

        <h1
          id="portfolio"
          className="mb-10 font-heading text-5xl tracking-widest text-white hover:tracking-wide"
        >
          port·​fo·​lio
        </h1>
        <p className="mr-10 ml-10 text-center font-bodyThinItalic text-white">
          <span className="decoration-coffee hover:line-through">
            1 : a hinged cover or flexible case for carrying loose papers,
            pictures, or pamphlets
          </span>
          <br />
          <span className="decoration-mint hover:line-through">
            2 [from the use of such a case to carry documents of state] : the
            office and functions of a minister of state or member of a cabinet
          </span>
          <br />
          <span className="decoration-creme hover:line-through">
            3 : the securities held by an investor : the commercial paper held
            by a financial house (such as a bank)
          </span>
          <br />
          <span className="decoration-white hover:line-through">
            4 : a set of pictures (such as drawings or photographs) usually
            bound in book form or loose in a folder
          </span>
          <span className="decoration-orange hover:underline">
            <br />5 : a selection of work compiled over a period of time and
            used for assessing performance or progress
          </span>
        </p>
        <br />
      </div>

      <div className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-charcoal to-mint">
        <p className="mt-96 font-bodyRegularItalic text-white">
          It all started with a
        </p>
        <h1 id="about" className="mb-3 font-heading text-5xl tracking-widest text-white hover:tracking-wide">
          Hello World;
        </h1>
        <p className="font-bodyRegularItalic text-white">
          and I knew I was hooked.
        </p>

        <p className="mx-10 mt-20 text-center font-bodyRegular text-white">
          On October 2020, I began learning how to code with the intention of
          being a software engineer. After a pandemic, a Javascript foundations course, a couple years of saving and an intensive software engineering course later, I have created several projects that I want to share to the world that I said hello to.
        </p>

        <p className="mx-10 mt-10 text-center font-bodyRegular text-white">As a growing software developer with a background in literature and a deep appreciation of art and design, I wanted a space to visually and dynamically showcase and tell the stories of the projects that I've been working on using the technologies I have learned, and continue to learn about.</p>

        <p className="mx-10 mt-10 text-center font-audreyNormal uppercase text-white"> Why programming?</p>

        <p className="mx-10 mt-10 text-center font-audreyNormal uppercase text-white"> What am I currently Learning?</p>
      </div>

      
      <div className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-mint to-mint">
        <h1>new</h1>
      </div>

      <div className="w-screen bg-gradient-to-b from-mint to-creme">
        <div id="projects" className="flex min-h-screen flex-col items-center justify-center">
          <p className="mb-5 font-heading text-5xl">study hero</p>
          <p className="font-bodyThin">
            A gamified pomodoro web application for game-lovers.
          </p>
        </div>
      </div>
      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-creme to-coffee">
        <p className="mb-5 font-heading text-5xl">cost of living</p>
        <p className="font-bodyThin text-center">
          {" "}
          A legacy project that helps people find their next home within their
          budget.
        </p>
      </div>
      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-coffee to-orange">
        <p className="mb-5 font-heading text-5xl">minimize</p>
        <p className="font-bodyThin">
          A tinder-style decluttering application.
        </p>
      </div>
      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-orange to-charcoal">
        <p className="mb-5 font-heading text-5xl">tokyo noire</p>
        <p className="font-bodyThin text-center">
          A geo-location, narrative based game platform and editor.
        </p>
      </div>
      <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-charcoal to-charcoal">
        <h1 id="contact" className="font-heading text-5xl text-white">contact me</h1>
        <h1 className="font-heading text-5xl text-white text-center">and let's collaborate</h1>
        <p className="mt-10 font-bodyRegular text-xl text-white">@instagram</p>
        <p className="font-bodyRegular text-xl text-white">@github</p>
        <p className="font-bodyRegular text-xl text-white">@linkedin</p>
        <p className="font-bodyRegular text-xl text-white">@email</p>
      </div>
    </>
  );
};

export default Home;